baseURL = "http://blog.mareksmidrkal.cz/lolek"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Barbara Šmidrkalová"
[[menu.main]]
name = "Kontakt"
url = "#contact"
weight = 2
[[menu.main]]
name = "Služby"
url = "#service"
weight = 1
[[menu.main-]]
name = "CV"
url = "#resume"
weight = 3
[[menu.main-]]
name = "Práce"
url = "#portfolio"
weight = 2
[[menu.main-]]
name = "O mně"
url = "#about"
weight = 1
[[menu.main-false]]
name = "Blog"
url = "#blog"
weight = 2
[[menu.main-false]]
name = "Home"
url = "#home"
weight = 1
[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "Všechna práva vyhrazena © Developed by MARUNA"
footerLogo = "images/site-navigation/logo-b.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo-b.png"
[params.address]
addressLine1 = "Odboje 55"
addressLine2 = "Litoměřice"
email = "barbara.smidrkalova@gmail.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "765 765 789"
[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social-false]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social-false]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
