backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images

collections:
  - label: "Sekce"
    name: "Kontakt"
    files:
      - label: "Kontakt"
        name: "kontakt"
        file: "content/contact/_index.md"
        fields:
          - {label: Hlavní nadpis, name: title, widget: string}
          
      - label: "O mně"
        name: "about"
        file: "data/aboutSection.yml"
        fields:
          - {label: Obsah boxu, name: content, widget: string}

      - label: "Nastavení webu"
        name: "config"
        file: "config.toml"
        fields:
          - label: "Einstellungen"
            name: "params"
            widget: "object"
            collapsed: "true"
            fields:
              - label: "Popis webu"
                label_singlar: "Popisek webu"
                name: "description"
                widget: "list"
                collpased: "true"
                fields:
                  - {label: description, name: description, widget: string}
