backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images

collections:
  - label: "Sekce"
    name: "Sekce"
    files:
      - label: "Úvod"
        name: "uvod"
        file: "data/aboutsection.yml"
        fields:
          - {label: title, name: title, widget: string}
          - {label: content, name: content, widget: markdown}
