---
label: Config Template
hide_body: true
fields:
- type: text
  name: baseURL
  label: baseURL
  hidden: false
- name: description
  type: text
  config:
    required: false
  label: Description tag
  description: Tag description v hlavičce webu
- type: text
  name: languageCode
  label: languageCode
  hidden: true
- type: text
  name: title
  label: Title tag webu
- type: text
  name: theme
  label: theme
  hidden: true
- type: number
  name: paginate
  label: paginate
  hidden: true
- type: field_group
  name: menu
  label: menu
  fields:
  - type: field_group_list
    name: main
    label: main
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: url
      label: url
    - type: number
      name: weight
      label: weight
    hidden: true
  - type: field_group_list
    name: sitemap
    label: sitemap
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: url
      label: url
    - type: number
      name: weight
      label: weight
    hidden: true
  hidden: true
- type: field_group
  name: params
  label: Obecná nastavení webu
  fields:
  - type: text
    name: blogPageURL
    label: blogPageURL
    hidden: true
  - type: file
    name: logo
    label: Logo
    description: Logo v hlavičce webu
  - type: file
    name: footerLogo
    label: footerLogo
    hidden: true
  - type: text
    name: contactLink
    label: contactLink
    hidden: true
  - type: text
    name: copyright
    label: Copyright v patičce webu
  - type: text
    name: googleAnalytics
    label: googleAnalytics
  - type: text
    name: formspreeURL
    label: formspreeURL
    hidden: true
  - type: field_group
    name: address
    label: Konakty
    fields:
    - type: text
      name: phone
      label: Telefon
    - type: text
      name: email
      label: Emailová adresa
    - type: text
      name: addressLine1
      label: První řádek adresy
    - name: addressLine2
      type: text
      config:
        required: false
      label: Druhý řádek adresy
    - type: text
      name: openingHours
      label: openingHours
      hidden: true
    description: Kontakty uvedené na stránce kontakty a v patičce webu.
  - type: field_group
    name: map
    label: map
    fields:
    - type: text
      name: APIkey
      label: APIkey
    - type: text
      name: latitude
      label: latitude
    - type: text
      name: longitude
      label: longitude
    - type: file
      name: pinImage
      label: pinImage
    hidden: true
  - name: footerJumbo
    type: field_group
    config: {}
    fields:
    - name: smallTitle
      type: text
      config:
        required: false
      label: Malý nadpis
    - name: bigTitle
      type: text
      config:
        required: false
      label: Velký nadpis
      description: Největší nadpis v boxu.
    - name: button
      type: text
      config:
        required: false
      label: Tlačítko
      description: Text tlačítka
    label: Velký box v patičce
    description: Nastavení textů ve velkém boxu v patičce webu.
pages:
- config.toml
