---
label: Config Template
hide_body: true
fields:
- type: text
  name: baseURL
  label: baseURL
  hidden: true
- type: text
  name: languageCode
  label: languageCode
  hidden: true
- type: text
  name: title
  label: Title tag webu
- type: text
  name: theme
  label: theme
  hidden: true
- type: number
  name: paginate
  label: paginate
  hidden: true
- type: field_group
  name: menu
  label: menu
  fields:
  - type: field_group_list
    name: main
    label: main
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: url
      label: url
    - type: number
      name: weight
      label: weight
  - type: field_group_list
    name: sitemap
    label: sitemap
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: url
      label: url
    - type: number
      name: weight
      label: weight
    hidden: true
- type: field_group
  name: params
  label: params
  fields:
  - type: text
    name: blogPageURL
    label: blogPageURL
    hidden: true
  - type: file
    name: logo
    label: Logo
    description: Logo v hlavičce webu
  - type: file
    name: footerLogo
    label: footerLogo
  - type: text
    name: contactLink
    label: contactLink
  - type: text
    name: copyright
    label: Copyright v patičce webu
  - type: text
    name: googleAnalytics
    label: googleAnalytics
  - type: text
    name: formspreeURL
    label: formspreeURL
    hidden: true
  - type: field_group
    name: address
    label: address
    fields:
    - type: text
      name: phone
      label: Telefon
    - type: text
      name: email
      label: Emailová adresa
    - type: text
      name: addressLine1
      label: První řádek adresy
    - name: addressLine2
      type: text
      config:
        required: false
      label: Druhý řádek adresy
    - type: text
      name: openingHours
      label: openingHours
      hidden: true
  - type: field_group
    name: map
    label: map
    fields:
    - type: text
      name: APIkey
      label: APIkey
    - type: text
      name: latitude
      label: latitude
    - type: text
      name: longitude
      label: longitude
    - type: file
      name: pinImage
      label: pinImage
    hidden: true
pages:
- config.toml
